name: Git Pull 13.0_test and Odoo Restart

on:
    push:
        branches:
            - 13.0_test

jobs:
    deploy-13-test:
        runs-on: ubuntu-latest
        steps:
            - name: SSH Comamnds
              uses: appleboy/ssh-action@master
              env:
                  PROJECT_PATH: ${{ secrets.PROJECT_PATH_TEST }}
              with:
                  host: "${{ secrets.SSH_HOST }}"
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY}}
                  envs: PROJECT_PATH
                  script: |
                      cd $PROJECT_PATH
                      git pull
                      git submodule update
